routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/licence', function () {
    return view('licence');
});

Auth::routes();
Auth::routes([
  'verify' => false,
  'reset' => false
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/usuarios', 'HomeController@users');
Route::post('/mision', 'HomeController@mision');
Route::get('/usuarios/{id}/edit', 'HomeController@editUser');
Route::PATCH('/usuarios/{id}', 'HomeController@updateUser');
Route::DELETE('/usuarios/{id}', 'HomeController@destroy');
Route::post('/rusuarios/{id}', 'HomeController@RestorePass');
Route::post('/rsusuarios/{id}', 'HomeController@ResetPass');
Route::get('/listu', 'HomeController@table');
Route::resource('computadoras', 'ComputadoraController');
Route::resource('impresoras', 'ImpresoraController');
Route::resource('routers', 'RouterController');
Route::resource('switches', 'SwitchController');
Route::resource('departamentos', 'DepartamentosController');
Route::resource('mantenimientos', 'MantenimientoController');
Route::resource('acciones', 'AccionesController');
Route::get('/lista', 'AccionesController@table');
Route::get('/listc', 'ComputadoraController@table');
Route::get('/listd', 'DepartamentosController@table');
Route::get('/listi', 'ImpresoraController@table');
Route::get('/listr', 'RouterController@table');
Route::get('/lists', 'SwitchController@table');
Route::get('/listm', 'MantenimientoController@table');
Route::get('/listcd', 'ComputadoraController@show');
Route::get('/listid', 'ImpresoraController@show');
Route::get('/listman', 'MantenimientoController@listR');
Route::get('/reportes', 'MantenimientoController@reportes');
Route::post('/cp', 'HomeController@CP');

app/Http/Controllers/AccionesController.php
<?php

namespace App\Http\Controllers;

use App\Accion;
use Illuminate\Http\Request;

class AccionesController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */

 public function __construct()
 {
     $this->middleware('auth');
 }

  public function index()
  {
      return view('acciones.index');
  }

  public function table()
  {
      $Acciones = Accion::all();
      return $Acciones;
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
      return view('acciones.create');

      //
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
      $request->validate([
          'accion' => 'required'
      ]);

      $Accion = new Accion([
          'accion'=> $request->get('accion')

      ]);
      $Accion->save();
      return redirect('acciones')->with('mensaje', 'Agregado con exito' );
    }


      //
      /**
       * Display the specified resource.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function show($id)
      {
          return Accion::find($id);
      }

      /**
       * Show the form for editing the specified resource.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function edit($id)
      {
          //
          $accion = Accion::findOrFail($id);
          return view('acciones.edit', compact('accion'));
      }

      /**
       * Update the specified resource in storage.
       *
       * @param  \Illuminate\Http\Request  $request
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
      public function update(Request $request, $id)
      {
          //
          $request->validate([
              'accion' => 'required'
          ]);

          $accion = Accion::find($id);
          $accion->accion= $request->get('accion');
          $accion->save();

          return redirect('acciones')->with('mensaje', 'Actualizado con exito' );
      }

      /**
       * Remove the specified resource from storage.
       *
       * @param  int  $id
       * @return \Illuminate\Http\Response
       */
       // public function destroy(Computadora $computadora)
     public function destroy($id)
      {
          //
          $accion = Accion::find($id);
          $accion->delete();
          return "Eliminado correctamente";

      }
}

resources/views/acciones/create.blade.php
@extends('layouts.app')
@section('content')
<style>
	.card-header{
		background-color: #4390dc;
		color: #ffffff;
	}
</style>

<div class="container">
	<div class="card-header">
		Agregar Acción de Mantenimiento
	</div>
	<div class="card-body">
		<form action="{{route('acciones.store')}}" method="post">
			{{ csrf_field() }}

			<div class="form-group">
				<label for="accion">Acción</label>
				<div class="col">
					<input type="text" class="form-control @error('accion') is-invalid @enderror" name="accion" value="{{old('accion')}}">

          @if ($errors->has('accion'))
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $errors->first('accion') }}</strong>
              </span>
          @endif
      	</div>
			</div>

			<button type="submit" class="btn btn-primary">Guardar</button>
			<a href="{{ url()->previous() }}" class="btn btn-danger">Cancelar</a>
		</form>
	</div>
</div>




@endsection

resources/views/acciones/edit.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Acciones Editar</title>
@endsection
@section('content')
  <style>
   	.card-header{
   		background-color: #3490dc;
   		color: #ffffff;
   	}
  </style>

	<div class="container">
		<div class="card-header">
			Editar Accion de Mantenimiento
		</div>

		<div class="card-body">

  		<form action="{{route('acciones.update', $accion->id)}}" method="post">
  			{{method_field('PATCH')}}
  			{{ csrf_field() }}

  			<div class="form-group">
  				<label for="accion">Acción</label>
  				<div class="col">
  					<input type="text" class="form-control @error('accion') is-invalid @enderror" name="accion" value="{{$accion->nombre}}">

            @if ($errors->has('accion'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('accion') }}</strong>
                </span>
            @endif
        	</div>
  			</div>

  			<button type="submit" class="btn btn-primary">Actualizar</button>
  			<a href="{{ url()->previous() }}" class="btn btn-danger">Cancelar</a>
  		</form>
		</div>
	</div>
@endsection

resources/views/acciones/index.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Acciones</title>
@endsection
@section('content')

  <div class="container">
    <h1>Acciones de Mantenimiento</h1>

    <hr/>

    @if(session()->get('mensaje'))
      <p id="EditMessage" hidden>
        {{session()->get('mensaje')}}
      </p>
    @endif
    <div id="toolbar">
      <p id="ActiveRoute" hidden>/acciones/</p>
      <a href="{{route('acciones.create')}}" title="Nuevo" class="btn btn-primary"><i class="fa fa-plus-circle"></i> </a>
      <button id="BtnEditar" title="Editar" class="btn btn-success"><i class="fa fa-edit"></i></button>
      <button id="BtnEliminar" title="Eliminar" class="btn btn-danger"><i class="fa fa-trash"></i></button>
    </div>
    <table
      id="tableInv"
      data-locale="es-MX"
      data-show-footer="true"
      data-show-refresh="true"
      data-toggle="table"
      data-sort-class="table-active"
      data-sortable="true"
      data-search="true"
      data-toolbar="#toolbar"
      data-single-select="true"
      data-click-to-select="true"
      data-page-list="[10, 25, 50, 100, All]"
      data-url="/lista"
      data-pagination="true">
      <thead>
        <tr>
          <th data-field="state" data-checkbox="true"></th>
          <th data-field="id" data-sortable="true">ID</th>
          <th data-field="accion" data-sortable="true">Acción</th>
        </tr>
      </thead>

    </table>
  </div>
@endsection