routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/licence', function () {
    return view('licence');
});

Auth::routes();
Auth::routes([
  'verify' => false,
  'reset' => false
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/usuarios', 'HomeController@users');
Route::post('/mision', 'HomeController@mision');
Route::get('/usuarios/{id}/edit', 'HomeController@editUser');
Route::PATCH('/usuarios/{id}', 'HomeController@updateUser');
Route::DELETE('/usuarios/{id}', 'HomeController@destroy');
Route::post('/rusuarios/{id}', 'HomeController@RestorePass');
Route::post('/rsusuarios/{id}', 'HomeController@ResetPass');
Route::get('/listu', 'HomeController@table');
Route::resource('computadoras', 'ComputadoraController');
Route::resource('impresoras', 'ImpresoraController');
Route::resource('routers', 'RouterController');
Route::resource('switches', 'SwitchController');
Route::resource('departamentos', 'DepartamentosController');
Route::resource('mantenimientos', 'MantenimientoController');
Route::resource('acciones', 'AccionesController');
Route::get('/lista', 'AccionesController@table');
Route::get('/listc', 'ComputadoraController@table');
Route::get('/listd', 'DepartamentosController@table');
Route::get('/listi', 'ImpresoraController@table');
Route::get('/listr', 'RouterController@table');
Route::get('/lists', 'SwitchController@table');
Route::get('/listm', 'MantenimientoController@table');
Route::get('/listcd', 'ComputadoraController@show');
Route::get('/listid', 'ImpresoraController@show');
Route::get('/listman', 'MantenimientoController@listR');
Route::get('/reportes', 'MantenimientoController@reportes');
Route::post('/cp', 'HomeController@CP');

app/Http/Controllers/SwitchController.php
<?php

namespace App\Http\Controllers;

use App\SwitchM;
use Illuminate\Http\Request;

class SwitchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

   public function __construct()
   {
       $this->middleware('auth');
   }

   public function new()
   {
       return view('switches.new');
   }

    public function index()
    {
        return view('switches.index');
    }

    public function table()
    {
        $Switches = SwitchM::all();
        return $Switches;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('switches.create');

        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'Marca' => 'required',
            'Caracteristicas'=> 'required',
            'ip_admin'=> 'required',
        ]);

        $Switch = new SwitchM([
            'Marca'=> $request->get('Marca'),
            'Caracteristicas'=> $request->get('Caracteristicas'),
            'ip_admin'=>$request->get('ip_admin')

        ]);
        $Switch->save();
        return redirect('switches')->with('mensaje', 'Agregado con exito' );
      }


        //
        /**
         * Display the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
            return SwitchM::find($id);
        }

        /**
         * Show the form for editing the specified resource.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function edit($id)
        {
            //
            $switch = SwitchM::findOrFail($id);
            return view('switches.edit', compact('switch'));
        }

        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function update(Request $request, $id)
        {
            //
            $request->validate([
                'Marca' => 'required',
                'Caracteristicas'=> 'required',
                'ip_admin'=> 'required',
            ]);

            $Switch = SwitchM::find($id);
            $Switch->Marca= $request->get('Marca');
            $Switch->Caracteristicas = $request->get('Caracteristicas');
            $Switch->ip_admin= $request->get('ip_admin');
            $Switch->save();

            return redirect('switches')->with('mensaje', 'Actualizado con exito' );
        }

        /**
         * Remove the specified resource from storage.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
         // public function destroy(Computadora $computadora)
       public function destroy($id)
        {
            //
            $Switch = SwitchM::find($id);
            $Switch->delete();
            return "Eliminado correctamente";

        }

 }

resources/views/switches/create.blade.php
@extends('layouts.app')
@section('content')
<style>
	.card-header{
		background-color: #4390dc;
		color: #ffffff;
	}
</style>

<div class="container">
	<div class="card-header">
		Agregar Switch
	</div>
	<div class="card-body">
		<form action="{{route('switches.store')}}" method="post">
			{{ csrf_field() }}

			<div class="form-group">
				<label for="marca">Marca</label>
                    <div class="col">
			<input type="text" class="form-control @error ('Marca') is-invalid  @enderror" name="Marca" value="{{old('Marca')}}">
			@if ($errors->has('Marca'))
					<span class="invalid-feedback" role="alert">
							<strong>{{ $errors->first('Marca') }}</strong>
					</span>
			@endif
                    </div>
                    </div>

		<div class="form-group">
				<label for="caracteristicas">Caracteristicas</label>
                    <div class="col">
			<input type="text" class="form-control @error ('Caracteristicas') is-invalid  @enderror" name="Caracteristicas" value="{{old('Caracteristicas')}}">
			@if ($errors->has('Caracteristicas'))
					<span class="invalid-feedback" role="alert">
							<strong>{{ $errors->first('Caracteristicas') }}</strong>
					</span>
			@endif
                    </div>
                    </div>

        <div class="form-group">
				<label for="ip_admin">IP Administrativa</label>
                    <div class="col">
			<input type="text" class="form-control @error ('ip_admin') is-invalid  @enderror" name="ip_admin" value="{{old('ip_admin')}}">
			@if ($errors->has('ip_admin'))
					<span class="invalid-feedback" role="alert">
							<strong>{{ $errors->first('ip_admin') }}</strong>
					</span>
			@endif
                    </div>
                    </div>

			<button type="submit" class="btn btn-primary">Guardar</button>
			<a href="{{ url()->previous() }}" class="btn btn-danger">Cancelar</a>
		</form>
	</div>
</div>




@endsection

resources/views/switches/edit.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Switches Editar</title>
@endsection
@section('content')
  <style>
   	.card-header{
   		background-color: #3490dc;
   		color: #ffffff;
   	}
  </style>

	<div class="container">
		<div class="card-header">
			Editar Switch
		</div>

		<div class="card-body">

  		<form action="{{route('switches.update', $switch->id)}}" method="post">
  			{{method_field('PATCH')}}
  			{{ csrf_field() }}
  		<div class="form-group">
				<label for="marca">Marca</label>
                    <div class="col">
			<input type="text" class="form-control @error ('Marca') is-invalid  @enderror" name="Marca" value="{{$switch->Marca}}">
      @if ($errors->has('Marca'))
          <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('Marca') }}</strong>
          </span>
      @endif
                    </div>
                    </div>

		<div class="form-group">
				<label for="caracteristicas">Caracteristicas</label>
                    <div class="col">
			<input type="text" class="form-control @error ('Caracteristicas') is-invalid  @enderror" name="Caracteristicas" value="{{$switch->Caracteristicas}}">
      @if ($errors->has('Caracteristicas'))
          <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('Caracteristicas') }}</strong>
          </span>
      @endif
                    </div>
                    </div>

        <div class="form-group">
				<label for="ip_admin">IP Administrativa</label>
                    <div class="col">
			<input type="text" class="form-control @error ('ip_admin') is-invalid  @enderror" name="ip_admin" value="{{$switch->ip_admin}}">
      @if ($errors->has('ip_admin'))
          <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('ip_admin') }}</strong>
          </span>
      @endif
                    </div>
                    </div>

  			<button type="submit" class="btn btn-primary">Actualizar</button>
  			<a href="{{ url()->previous() }}" class="btn btn-danger">Cancelar</a>
  		</form>
		</div>
	</div>
@endsection

resources/views/switches/index.blade.php
@extends('layouts.app')

@section('titulo')
  <title>Switches</title>
@endsection
@section('content')

  @if(session()->get('mensaje'))
    <p id="EditMessage" hidden>
  		{{session()->get('mensaje')}}
  	</p>
  @endif
  <div class="container">
  	<h1>Switches</h1>

  	<hr/>
    <div id="toolbar">
      <p id="ActiveRoute" hidden>/switches/</p>
      @if (Auth::user()->tipo_cargo != 'Dirección')
        <a href="{{route('switches.create')}}" title="Nuevo" class="btn btn-primary"><i class="fa fa-plus-circle"></i> </a>
        <button id="BtnEditar" title="Editar" class="btn btn-success"><i class="fa fa-edit"></i></button>
        <button id="BtnEliminar" title="Eliminar" class="btn btn-danger"><i class="fa fa-trash"></i></button>
      @endif
    </div>
    <table
      id="tableInv"
      data-locale="es-MX"
      data-show-footer="true"
      data-show-export="true"
      data-export-types='["json", "xml", "csv", "txt", "pdf"]'
      data-export-options='{"fileName": "Switches", "jspdf": {"orientation":"landscape", "margins":{"left":30,"right":30,"bottom":30,"top":30}}}'
      data-show-refresh="true"
      data-toggle="table"
      data-sort-class="table-active"
      data-sortable="true"
      data-search="true"
      data-toolbar="#toolbar"
      data-page-list="[10, 25, 50, 100, All]"
      data-single-select="true"
      data-click-to-select="true"
      data-url="/lists"
      data-pagination="true">
      <thead>
        <tr>
          <th data-field="state" data-checkbox="true"></th>
          <th data-field="id" data-sortable="true">ID</th>
          <th data-field="Marca" data-sortable="true">Marca</th>
          <th data-field="Caracteristicas" data-sortable="true">Caracteristicas</th>
          <th data-field="ip_admin" data-sortable="true">IP Administrativa</th>
        </tr>
      </thead>

    </table>
  </div>
@endsection